// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFr0zVYYikd-Jpi7DLE1cbvC6fQqj9ICk',
    appId: '1:599326853520:android:37304e352c72f6160f4b15',
    messagingSenderId: '599326853520',
    projectId: 'flutter-brycen-chat-app',
    databaseURL: 'https://flutter-brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-brycen-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjER53vLjLARHaWrDANWX7aGBAJZ7xS8',
    appId: '1:599326853520:ios:ec82e4d173864a550f4b15',
    messagingSenderId: '599326853520',
    projectId: 'flutter-brycen-chat-app',
    databaseURL: 'https://flutter-brycen-chat-app-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-brycen-chat-app.appspot.com',
    iosClientId: '599326853520-hfki3u0cqevmb62vhvfg3s3ahmg9th4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
